name: Testar Envio de Email

on:
  workflow_dispatch:

jobs:
  test-email:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código no repositório
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install smtplib email  # Instalar diretamente as bibliotecas necessárias

    - name: Enviar Email de Teste
      run: |
        python seu_script_de_envio_de_email.py  # Substitua pelo caminho correto para o seu script
      env:
        GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
        GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}
        GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}
