jobs:
  send_email:
    runs-on: ubuntu-latest

    env:
      GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
      GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}
      GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Verificar variáveis de ambiente
        run: |
          echo "Sender: $GMAIL_SENDER"
          echo "Recipient: $GMAIL_RECIPIENT"
          echo "App Password: $GMAIL_APP_PW"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install secure-smtplib

      - name: Enviar e-mail
        run: python send_email.py
