name: Enviar E-mail

on:
  workflow_dispatch:  # permite disparo manual pelo botão “Run workflow”

jobs:
  send_email:
    runs-on: ubuntu-latest
    environment: spinarak

    env:
      GMAIL_SENDER:    ${{ secrets.GMAIL_SENDER }}
      GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}
      GMAIL_APP_PW:    ${{ secrets.GMAIL_APP_PW }}

    steps:
      - uses: actions/checkout@v2

      - name: Verificar variáveis de ambiente
        run: |
          echo "Sender set? $( [ -z \"$GMAIL_SENDER\" ] && echo no || echo yes )"
          echo "Recipient set? $( [ -z \"$GMAIL_RECIPIENT\" ] && echo no || echo yes )"
          echo "App Password set? $( [ -z \"$GMAIL_APP_PW\" ] && echo no || echo yes )"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install secure-smtplib

      - name: Enviar e-mail
        run: python send_email.py
