      - name: Run Python Selenium script
        env:
          GMAIL_SENDER:      ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PW:      ${{ secrets.GMAIL_APP_PW }}
          GMAIL_RECIPIENT:   ${{ secrets.GMAIL_RECIPIENT }}
          GMAIL_RECIPIENT_two: ${{ secrets.GMAIL_RECIPIENT_two }}
          CAPSOLVER_API_KEY: ${{ secrets.CAPSOLVER_API_KEY }}  # 👈 ADICIONA ESTA LINHA
        run: |
          echo -e "current NAT'd source IP address: $(curl -s api.ipify.org)\n"
          python spinarak.py
          ls -al
